### ISSUE TITLE
_distro version in module ${project.parent.version}

### ISSUE THREAD

**Issue by stbischof** [effectiveosgi/eosgi-runtime#1]
Hi Neil,

thanks for the maven-archetypes and the examples!!

wouldn`t it be be better to use the ${project.parent.version} and not the ${project.version} when linking the distro into module and test pom files?

><dependency>
	<groupId>${project.groupId}</groupId>
	<artifactId>_distro</artifactId>
	<version>${project.parent.version}</version>
	<scope>runtime</scope>
	<type>pom</type>
</dependency>

So your artefacts/bundles can have different version without getting trouble with the distro.

Thanks
Stefan

**Comment by njbartlett** [comment]
Yes that does sound like a sensible change. Thank you!

**Comment by njbartlett** [comment]
Fixed in https://github.com/effectiveosgi/maven-archetypes/commit/628ab937a322e56281afecf3cf8477179c11214e
